version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/formfactory.pfx
      - ASPNETCORE_URLS=https://+:8081

  frontend:
    build: .
    ports:
      - "3030:80"
    depends_on:
      - backend
