version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  form-factory:
    container_name: form-factory
    build: .
    ports:
      - "4065:80"
    depends_on:
      - db

volumes:
  postgres_data:
