export default {
  id: 1994,
  title: "Pet survey",
  published: "2018-01-10",
  components: [
    {
      id: 1,
      label: "If you have animals, how many animals do you have?",
      componentType: "textfield",
      inputType: "number",
      required: true,
      greaterThan: undefined,
      lessThan: 3,
    },
    {
      id: 2,
      label: "Do you prefer dogs or cats?",
      componentType: "radio",
      choices: ["Dogs", "Cats"],
    },
    {
      id: 3,
      label: "If you don't have animals, would you consider becoming an animal owner?",
      componentType: "textfield",
      inputType: "string",
      required: true,
      minLength: 2,
      maxLength: 300,
    },
    {
      id: 4,
      label: "If you would get a new pet, what animal would it be?",
      componentType: "radio",
      choices: ["Dog", "Cat", "Horse", "Cow", "Chicken"],
    },
    {
      id: 5,
      label: "What is the main factor in choosing a pet?",
      componentType: "textfield",
      inputType: "string",
      required: true,
      minLength: 0,
      maxLength: 200,
    },
    {
      id: 6,
      label: "Have you ever adopted a pet from a shelter?",
      componentType: "radio",
      choices: ["Yes", "No"],
    },
  ],
};
