name: Backend test

on:
  push:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Check formatting
        run: dotnet format backend/FormAPI.sln --verify-no-changes --verbosity detailed

      - name: Test
        run: dotnet test backend/FormAPI.sln --no-restore
