name: Frontend build, lint, and typecheck no-matrix

on:
  push:
    paths-ignore:
      - "backend/**"

jobs:
  build-lint-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install
        
      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
        
      - name: Typecheck
        run: yarn typecheck
